### ISSUE TITLE
Grafana dashboard 

### ISSUE THREAD

**Issue by ibaarani** [slashdoom/aruba_exporter#1]
hello team  , 
     hope you are all doing great can we have the grafana dashboard ?

**Comment by slashdoom** [comment]
This is all a work-in-progress, but I've added the dashboards I've been using so far in:
[aruba_exporter](https://github.com/slashdoom/aruba_exporter)/[samples](https://github.com/slashdoom/aruba_exporter/tree/main/samples)/[dashboards](https://github.com/slashdoom/aruba_exporter/tree/main/samples/dashboards)/
