### ISSUE TITLE
key based access

### ISSUE THREAD

**Issue by felixn-unity** [slashdoom/aruba_exporter#2]
Hi

Great project!

Key based aithentication don't seem to work. If I manually try to access my Aruba switch it works fine.

I tried to troubleshoot the code and all looks good, you have any hint on how I can troubleshoot it further?

Thanks
Felix

**Comment by felixn-unity** [comment]
sorry it do seem to work - is related to group permissions it looks like

**Comment by slashdoom** [comment]
Thanks for testing.
